target 'IFGExtensions_Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '13.0'
  
  pod 'IFGExtensions', :path => '../'
end
